project_id = "vwrgnlpajtwifbgyiutk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://vwrgnlpajtwifbgyiutk.supabase.co"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }} ."

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true
port = 54325
tenant_id = "realtime-dev"

[studio]
enabled = true
port = 54323

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"

[edge_runtime]
enabled = true
port = 54326

[inbucket]
enabled = true
port = 54327
smtp_port = 54328
pop3_port = 54329

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.create-donation-payment]
verify_jwt = true

[functions.verify-donation-payment]
verify_jwt = true