// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwrgnlpajtwifbgyiutk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3cmdubHBhanR3aWZiZ3lpdXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDI1NzMsImV4cCI6MjA2MzkxODU3M30.gFv5gbOMyVPArjySwnaQmHDHhM0L47kOX4sjjREbIZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

declare global {
  // eslint-disable-next-line no-var
  var __supabase__: SupabaseClient<Database> | undefined;
}

export const supabase: SupabaseClient<Database> =
  globalThis.__supabase__ ??
  (globalThis.__supabase__ = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY));